# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
target 'HalfCandy' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HalfCandy
pod 'MJRefresh'
pod 'JPFPSStatus', '~> 0.0.2'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'YYModel'
pod 'MJExtension'
pod 'Masonry'


end
